module bf16_mul (a, b, result);

    input  logic [15:0] a;
    input  logic [15:0] b;
    output logic [15:0] result;

    // 1. Unpack
    logic sign_a, sign_b;
    logic [6:0] mantissa_a, mantissa_b;
    logic [7:0] exponent_a, exponent_b;

    assign sign_a = a[15];
    assign sign_b = b[15];

    assign exponent_a = a[14:7];
    assign exponent_b = b[14:7];

    assign mantissa_a = a[6:0];
    assign mantissa_b = b[6:0];

    // 2. Sign
    logic sign_output;
    assign sign_output = sign_a ^ sign_b;

    // 3. Exponent, add and remove one bias
    logic [8:0] out_exponent;
    assign out_exponent = exponent_a + exponent_b - 127;

    // 4. Mantissa, prepend hidden 1 and multiply
    logic [7:0] temp_mantissa_a, temp_mantissa_b;
    assign temp_mantissa_a = {1'b1, mantissa_a};
    assign temp_mantissa_b = {1'b1, mantissa_b};

    logic [15:0] mant_product;
    assign mant_product = temp_mantissa_a * temp_mantissa_b;

    // 5. Normalize
    logic [8:0] exp_result;
    logic [6:0] mant_result;

    always_comb begin
        if (mant_product[15]) begin
            mant_result = mant_product[14:8];
            exp_result  = out_exponent + 1'b1;
        end else begin
            mant_result = mant_product[13:7];
            exp_result  = out_exponent;
        end
    end

    // 6. Pack
    always_comb begin
        if (exp_result[8]) begin
            // Exponent overflow
            result = {sign_output, 8'hFF, 7'h00};
        end else begin
            result = {sign_output, exp_result[7:0], mant_result};
        end
    end

endmodule

module bf16_mul_tb ();

    // --------------------------------------------------------
    // 1. Declare signals to connect to the DUT (Device Under Test)
    // --------------------------------------------------------
    logic [15:0] a;
    logic [15:0] b;
    logic [15:0] result;

    // 2. Instantiate the multiplier module
    bf16_mul dut (
        .a(a),
        .b(b),
        .result(result)
    );

    // --------------------------------------------------------
    // 3. Variables for File I/O and Verification
    // --------------------------------------------------------
    int file_handle;
    int scan_return;
    logic [15:0] expected_result;
    
    int error_count = 0;
    int test_count = 0;

    // --------------------------------------------------------
    // 4. Test Sequence
    // --------------------------------------------------------
    initial begin
        // Open the text file generated by the Python Golden Model.
        // NOTE: Ensure this path matches your folder structure!
        file_handle = $fopen("mul_vectors.txt", "r");

        if (file_handle == 0) begin
            $display("FATAL ERROR: Could not open mul_vectors.txt! Check your file path.");
            $finish;
        end

        $display("==================================================");
        $display("Starting BF16 Multiplier File-Based Testbench...");
        $display("==================================================");

        // Loop through the file line by line until we hit the end (EOF)
        while (!$feof(file_handle)) begin
            
            // Read three 4-character hex strings per line
            // %h tells SystemVerilog to expect hexadecimal data
            scan_return = $fscanf(file_handle, "%h %h %h\n", a, b, expected_result);

            // If we successfully read all 3 values, test them
            if (scan_return == 3) begin
                
                #10; // Wait 10 time units for combinational logic to settle

                // Check if the physical hardware result matches the Python golden model
                if (result !== expected_result) begin
                    $display("ERROR at Test %0d:", test_count);
                    $display("  Input A  : %h", a);
                    $display("  Input B  : %h", b);
                    $display("  Expected : %h", expected_result);
                    $display("  Got      : %h", result);
                    error_count++;
                end
                
                test_count++;
            end
        end

        // Close the file and report the final score
        $fclose(file_handle);

        $display("==================================================");
        if (error_count == 0) begin
            $display("SUCCESS: All %0d vectors passed! The multiplier is flawless.", test_count);
        end else begin
            $display("FAILED: %0d out of %0d vectors failed.", error_count, test_count);
        end
        $display("==================================================");

        $finish;
    end

endmodule